[env]
build_flags =

    # Your Blynk credentials HERE
    -DBLYNK_TEMPLATE_ID=\"EXEMPLE\"
    -DBLYNK_TEMPLATE_NAME=\"ExempleName\"
    -DBLYNK_AUTH_TOKEN=\"EXEMPLE-TOKEN\"
    
    # Your Wifi network HERE
    -DWIFI_SSID=\"Exemple-SSID\"
    -DWIFI_PASS=\"Exemple-PASS\"