[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = https://github.com/Blynk-Technologies/blynk-library.git
            https://github.com/ropg/eztime

build_flags = 
    -I include/Siren
    -I include/Observer